name: Запуск Ядра

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: ЗАПУСК КОМПИЛЯТОРА
      run: python src/main.py examples/тест.яд
